name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      continue:
        description: 'Approve deployment'
        required: true
        default: 'false'

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Analyze with SonarQube
        id: sonar
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  quality-gate:
    runs-on: ubuntu-latest
    needs: analysis
    outputs:
      quality-gate-status: ${{ steps.get-quality-gate-status.outputs.quality-gate-status }}
    steps:
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Get SonarQube Quality Gate Status
        id: get-quality-gate-status
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

  notify-approval:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
      - name: Notify on Google Chat for approval
        if: always()
        run: |
          MESSAGE="SonarQube analysis completed. Quality Gate status: ${{ needs.quality-gate.outputs.quality-gate-status }}. Please approve the deployment."
          APPROVAL_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-Type: application/json' \
          -d '{
            "cards": [
              {
                "header": {
                  "title": "Deployment Approval Request",
                  "subtitle": "'"$MESSAGE"'"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "buttons": [
                          {
                            "textButton": {
                              "text": "APPROVE DEPLOYMENT",
                              "onClick": {
                                "openLink": {
                                  "url": "'"$APPROVAL_URL"'"
                                }
                              }
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }' "${{ secrets.PROAPPROVAL }}"

  approval:
    runs-on: ubuntu-latest
    needs: notify-approval
    if: github.event.inputs.continue == 'true'
    steps:
      - name: Approval granted
        run: echo "Deployment approved manually"

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy application
        run: echo "Deploying the application..."
