name: SonarQube analysis

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      continue:
        description: "Approve deployment"
        required: true
        default: "false"

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze with SonarQube
        id: sonar
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: "Here is SonarQube Quality Gate Status value.."
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

  notify-approval:
    runs-on: ubuntu-latest
    needs: Analysis
    steps:
      - name: Notify on Google Chat for approval
        if: always()
        run: |
          MESSAGE="El analisis de Sonarqube terminó. Por favor aproba esto asi sigo laburando, sino, no voy a laburar."
          APPROVAL_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-Type: application/json' \
          -d '{
            "cards": [
              {
                "header": {
                  "title": "Deployment Approval Request",
                  "subtitle": "'"$MESSAGE"'"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "buttons": [
                          {
                            "textButton": {
                              "text": "APPROVE DEPLOYMENT",
                              "onClick": {
                                "openLink": {
                                  "url": "'"$APPROVAL_URL"'"
                                }
                              }
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }' "${{ secrets.PROAPPROVAL }}"

  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Google Chat
        run: |
          GOOGLE_CHAT_ROOM="xYO8qkAAAAE"
          MESSAGE="Deployment approval request. Click [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) to approve."

          curl -X POST -H 'Content-Type: application/json' \
          -d '{
            "text": "'"$MESSAGE"'"
          }' "${{ secrets.PROAPPROVAL }}"

  notify-after-deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy-prod
    steps:
      - name: Notify on Google Chat after deploy
        if: success()
        run: |
          GOOGLE_CHAT_ROOM="xYO8qkAAAAE"
          MESSAGE="Deployment and approval request is done."
          curl -X POST -H 'Content-Type: application/json' \
           -d '{
            "text": "'"$MESSAGE"'"
          }' "${{ secrets.PROAPPROVAL }}"
