name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Analyze with SonarQube
        id: sonar
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          
      - name: Quality Gate status
        run: |
          status=$(curl -s -u ${SONAR_TOKEN}: ${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} | jq -r .projectStatus.status)
          if [ "$status" != "OK" ]; then
            echo "Quality Gate failed: $status"
            exit 1
          else
            echo "Quality Gate passed: $status"
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
